CREATE TABLE IF NOT EXISTS Начальник (
	ID SERIAL PRIMARY KEY,
	Имя VARCHAR(100) NOT null
);

CREATE TABLE IF NOT EXISTS Отдел (
	ID SERIAL PRIMARY KEY,
	Название VARCHAR(100) NOT null
);

CREATE TABLE IF NOT EXISTS Сотрудник (
	ID SERIAL PRIMARY KEY,
	Имя VARCHAR(100) NOT null,
	Начальник_ID SERIAL REFERENCES Начальник(ID),
	Отдел_ID SERIAL REFERENCES Отдел(ID)
);
