CREATE TABLE IF NOT EXISTS Genre(
	GenreID SERIAL PRIMARY KEY,
	Genre_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Musician (
	MusicianID SERIAL PRIMARY KEY,
	Stage_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Album (
	AlbumID SERIAL PRIMARY KEY,
	Title VARCHAR(100) NOT NULL,
	Release_year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Music_track (
	TrackID SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	Duration INTEGER NOT NULL,
	AlbumID SERIAL REFERENCES Album(AlbumID)
);

CREATE TABLE IF NOT EXISTS Musician_Genre (
	MusicianID SERIAL NOT NULL REFERENCES Musician(MusicianID),
	GenreID SERIAL NOT NULL REFERENCES Genre(GenreID),
	CONSTRAINT Musician_Genre_pk PRIMARY KEY (MusicianID, GenreID)
);

CREATE TABLE IF NOT EXISTS Musician_Album (
	MusicianID SERIAL NOT NULL REFERENCES Musician(MusicianID),
	AlbumID SERIAL NOT NULL REFERENCES Album(AlbumID),
	CONSTRAINT Musician_Album_pk PRIMARY KEY (MusicianID, AlbumID)
);

CREATE TABLE IF NOT EXISTS Collection (
	CollectionID SERIAL PRIMARY KEY,
	Title VARCHAR(100) NOT NULL,
	Release_year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Collection_Track (
	CollectionID SERIAL NOT NULL REFERENCES Collection(CollectionID),
	TrackID SERIAL NOT NULL REFERENCES Music_track(TrackID),
	CONSTRAINT Collection_Track_pk PRIMARY KEY (CollectionID, TrackID)
);
